committing
Samantha-KY/BEMClone pull request #1
Opened 2022-09-28 08:35 UTC by Samiskina

2022-09-28 08:59 UTC, mbukeRepo requested changes

2022-09-28 08:59 UTC, mbukeRepo commented on style.css
> +.intro__body__card{
Try to avoid nesting elements.

2022-09-28 08:59 UTC, mbukeRepo commented on style.css
> +.intro__body__card__el{
Try to avoid nesting.

2022-09-29 06:28 UTC, mbukeRepo approved these changes
LGTM

2022-09-29 09:23 UTC, rithaven commented on style.css
> +.body{
It's better to style body at the top of your css. (nesting of blocks and elements)

2022-09-29 09:27 UTC, rithaven commented on style.css
> +.nav__list__side{
Write this element right element format. like **nav__list-side** or if it is a modifier write **nav__list--side**

2022-09-29 09:28 UTC, rithaven commented on style.css
> +    .nav__list__line{
Change this also

2022-09-29 09:39 UTC, rithaven commented on index.html
> -         class="intro__body__card"
Use right way of writing elements.  hint : intro__body-card or intro__body---card if it is a modifier

2022-09-29 09:56 UTC, rithaven approved these changes
Good Job

2022-09-29 15:12 UTC, karemarsy reviewed
I can't see your html file, I don't know why

2022-09-29 15:39 UTC, Samiskina commented
Could you use this link; I don't know why it is not visible.
https://github.com/Samiskina/BEMClone/pull/1/commits/e6da14d60f760e571085311d131425b68026050f

On Thu, Sep 29, 2022 at 5:12 PM Karema Arsene ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
>
> I can't see your html file, I don't know why
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Samiskina/BEMClone/pull/1#pullrequestreview-1125497697>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUTYTVECAGZJ3OU66O2VQ6TWAWWVPANCNFSM6AAAAAAQXRBFDE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-03 11:55 UTC, karemarsy approved these changes

2022-10-04 13:41 UTC, karemarsy commented on index.html
> +            <div class="intro__card-el1 intro__body--display">
`intro__body--display` is included without it's default Element (intro__body).

2022-10-04 13:41 UTC, karemarsy commented on index.html
> +            <div class="intro__card-el1 intro__body--display">
`intro__body--display` is included without it's default Element (intro__body).

2022-10-04 13:41 UTC, karemarsy commented on index.html
> +            <div class="intro__card-el1 intro__body--display">
`intro__body--display` is included without it's default Element (intro__body).

2022-10-04 13:41 UTC, karemarsy commented on index.html
> +            <div class="intro__card-el1 intro__body--display">
`intro__body--display` is included without it's default Element (intro__body).

2022-10-04 13:41 UTC, karemarsy commented on index.html
> +            <div class="intro__card-el1 intro__body--display">
`intro__body--display` is included without it's default Element (intro__body).

2022-10-04 13:41 UTC, karemarsy commented on index.html
> +            <div class="intro__card-el1 intro__body--display">
`intro__body--display` is included without it's default Element (intro__body).

2022-10-04 13:41 UTC, karemarsy commented on index.html
> +    <div class="footer__text">
`footer__text` is positioned outside the Block (footer).

2022-10-04 13:41 UTC, karemarsy commented on index.html
> +      <p class="footer__parag footer__parag--color">
`footer__parag` is positioned outside the Block (footer).
`footer__parag--color` is positioned outside the Block (footer).

2022-10-06 14:05 UTC, merged